project_id = "favqubkxorqhhuguekxg"

[functions.get-lyrics]
verify_jwt = false

[functions.sync-google-sheets]
verify_jwt = false

[functions.verify-dj-pin]
verify_jwt = false

[functions.update-settings]
verify_jwt = false

[functions.recognize-song]
verify_jwt = false
